CREATE TABLE IF NOT EXISTS incomes (
    id SERIAL PRIMARY KEY,
    description TEXT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    month INT NOT NULL,
    year INT NOT NULL
);