ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS installment_number   INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS installment_total    INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS installment_group_id INTEGER DEFAULT NULL;
